# --- Build Stage ---
FROM maven:3.9.6-eclipse-temurin-17 as builder

WORKDIR /app
COPY . .

RUN mvn clean package -DskipTests

# --- Run Stage ---
FROM eclipse-temurin:17-jdk

WORKDIR /app
COPY --from=builder /app/target/*.jar app.jar

ENV PORT=8080
EXPOSE 8080

CMD ["java", "-jar", "app.jar"]   # ✅ IMPORTANT

